"""empty message

Revision ID: 5842f8cf34a2
Revises: c8cbf2689ec8
Create Date: 2020-06-30 00:28:09.370528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5842f8cf34a2'
down_revision = 'c8cbf2689ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    # ### end Alembic commands ###
